name: Deploy to GitHub Pages
on:
  push:
    branches:
      - dev
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Create .nojekyll 📄
        run: touch .nojekyll
      - name: Inject Secrets into emailsend.js 💉
        run: |
          sed -i 's/process.env.EMAIL_HOST_USER/"${{ secrets.EMAIL_HOST_USER }}"/g' emailsend.js
          sed -i 's/process.env.EMAIL_HOST_PASSWORD/"${{ secrets.EMAIL_HOST_PASSWORD }}"/g' emailsend.js
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages